import type { CatalogGroup } from "./osrs-catalog";

export const SKILLING_GROUPS: CatalogGroup[] = [
  {
    id: "herblore",
    label: "Herblore",
    kind: "skilling",
    note: "Wiki-recommended potion training (unf + secondary) and herb cleaning",
    items: [
      { name: "Grimy guam leaf", tags: ["herblore"] },
      { name: "Guam leaf", tags: ["herblore"] },
      { name: "Grimy marrentill", tags: ["herblore"] },
      { name: "Marrentill", tags: ["herblore"] },
      { name: "Grimy tarromin", tags: ["herblore"] },
      { name: "Tarromin", tags: ["herblore"] },
      { name: "Grimy harralander", tags: ["herblore"] },
      { name: "Harralander", tags: ["herblore"] },
      { name: "Grimy ranarr weed", tags: ["herblore"] },
      { name: "Ranarr weed", tags: ["herblore"] },
      { name: "Grimy toadflax", tags: ["herblore"] },
      { name: "Toadflax", tags: ["herblore"] },
      { name: "Grimy irit leaf", tags: ["herblore"] },
      { name: "Irit leaf", tags: ["herblore"] },
      { name: "Grimy avantoe", tags: ["herblore"] },
      { name: "Avantoe", tags: ["herblore"] },
      { name: "Grimy kwuarm", tags: ["herblore"] },
      { name: "Kwuarm", tags: ["herblore"] },
      { name: "Grimy huasca", tags: ["herblore"] },
      { name: "Huasca", tags: ["herblore"] },
      { name: "Grimy snapdragon", tags: ["herblore"] },
      { name: "Snapdragon", tags: ["herblore"] },
      { name: "Grimy cadantine", tags: ["herblore"] },
      { name: "Cadantine", tags: ["herblore"] },
      { name: "Grimy lantadyme", tags: ["herblore"] },
      { name: "Lantadyme", tags: ["herblore"] },
      { name: "Grimy dwarf weed", tags: ["herblore"] },
      { name: "Dwarf weed", tags: ["herblore"] },
      { name: "Grimy torstol", tags: ["herblore"] },
      { name: "Torstol", tags: ["herblore"] },
      { name: "Snape grass", tags: ["herblore"] },
      { name: "Crushed nest", tags: ["herblore"] },
      { name: "Wine of zamorak", tags: ["herblore"] },
      { name: "Mort myre fungus", tags: ["herblore"] },
      { name: "Vial of water", tags: ["herblore"] },
      { name: "Amylase crystal", tags: ["herblore"] },
      { name: "Cup of hot water", tags: ["herblore"] },
      { name: "Rainbow crab paste", tags: ["herblore"] },
      { name: "Amulet of chemistry", tags: ["herblore"] },
      { name: "Earth rune", tags: ["herblore", "magic", "runecraft"] },
    ],
  },
  {
    id: "construction",
    label: "Construction",
    kind: "skilling",
    note: "POH tables/benches/doors, mythical capes, hull parts & repair kits",
    items: [
      { name: "Oak plank", tags: ["construction"] },
      { name: "Teak plank", tags: ["construction"] },
      { name: "Mahogany plank", tags: ["construction"] },
      { name: "Plank", tags: ["construction"] },
      { name: "Steel bar", tags: ["construction", "smithing"] },
      { name: "Bolt of cloth", tags: ["construction"] },
      { name: "Limestone brick", tags: ["construction"] },
      { name: "Gold leaf", tags: ["construction"] },
      { name: "Marble block", tags: ["construction"] },
      { name: "Magic stone", tags: ["construction"] },
      { name: "Mahogany hull parts", tags: ["construction"] },
      { name: "Mahogany repair kit", tags: ["construction"] },
      { name: "Mithril nails", tags: ["construction"] },
      { name: "Swamp paste", tags: ["construction"] },
    ],
  },
  {
    id: "prayer",
    label: "Prayer",
    kind: "skilling",
    note: "Bones (gilded/chaos/shards), offering spells, ensouled heads",
    items: [
      { name: "Big bones", tags: ["prayer"] },
      { name: "Dragon bones", tags: ["prayer"] },
      { name: "Wyrm bones", tags: ["prayer"] },
      { name: "Lava dragon bones", tags: ["prayer"] },
      { name: "Dagannoth bones", tags: ["prayer"] },
      { name: "Hydra bones", tags: ["prayer"] },
      { name: "Superior dragon bones", tags: ["prayer"] },
      { name: "Fiendish ashes", tags: ["prayer"] },
      { name: "Vile ashes", tags: ["prayer"] },
      { name: "Malicious ashes", tags: ["prayer"] },
      { name: "Abyssal ashes", tags: ["prayer"] },
      { name: "Infernal ashes", tags: ["prayer"] },
      { name: "Ensouled goblin head", tags: ["prayer"] },
      { name: "Ensouled monkey head", tags: ["prayer"] },
      { name: "Ensouled imp head", tags: ["prayer"] },
      { name: "Ensouled minotaur head", tags: ["prayer"] },
      { name: "Ensouled scorpion head", tags: ["prayer"] },
      { name: "Ensouled bear head", tags: ["prayer"] },
      { name: "Ensouled unicorn head", tags: ["prayer"] },
      { name: "Ensouled dog head", tags: ["prayer"] },
      { name: "Ensouled chaos druid head", tags: ["prayer"] },
      { name: "Ensouled giant head", tags: ["prayer"] },
      { name: "Ensouled ogre head", tags: ["prayer"] },
      { name: "Ensouled elf head", tags: ["prayer"] },
      { name: "Ensouled troll head", tags: ["prayer"] },
      { name: "Ensouled horror head", tags: ["prayer"] },
      { name: "Ensouled kalphite head", tags: ["prayer"] },
      { name: "Ensouled dagannoth head", tags: ["prayer"] },
      { name: "Ensouled bloodveld head", tags: ["prayer"] },
      { name: "Ensouled tzhaar head", tags: ["prayer"] },
      { name: "Ensouled demon head", tags: ["prayer"] },
      { name: "Ensouled hellhound head", tags: ["prayer"] },
      { name: "Ensouled aviansie head", tags: ["prayer"] },
      { name: "Ensouled abyssal head", tags: ["prayer"] },
      { name: "Ensouled dragon head", tags: ["prayer"] },
    ],
  },
  {
    id: "crafting",
    label: "Crafting",
    kind: "skilling",
    note: "Glassblowing, d'hide bodies, battlestaves and amethyst tips",
    items: [
      { name: "Molten glass", tags: ["crafting"] },
      { name: "Giant seaweed", tags: ["crafting"] },
      { name: "Bucket of sand", tags: ["crafting"] },
      { name: "Green dragon leather", tags: ["crafting"] },
      { name: "Blue dragon leather", tags: ["crafting"] },
      { name: "Red dragon leather", tags: ["crafting"] },
      { name: "Black dragon leather", tags: ["crafting"] },
      { name: "Battlestaff", tags: ["crafting"] },
      { name: "Air orb", tags: ["crafting"] },
      { name: "Water orb", tags: ["crafting"] },
      { name: "Uncut diamond", tags: ["crafting"] },
      { name: "Gold bar", tags: ["crafting", "smithing"] },
      { name: "Amethyst", tags: ["crafting", "mining"] },
      { name: "Amethyst bolt tips", tags: ["crafting", "fletching"] },
      { name: "Amethyst arrowtips", tags: ["crafting", "fletching"] },
      { name: "Amethyst javelin tips", tags: ["crafting", "fletching"] },
      { name: "Amethyst dart tip", tags: ["crafting", "fletching"] },
    ],
  },
  {
    id: "smithing",
    label: "Smithing & Mining",
    kind: "skilling",
    note: "Blast furnace, dart tips, nails, cannonballs, armour",
    items: [
      { name: "Copper ore", tags: ["smithing", "mining"] },
      { name: "Tin ore", tags: ["smithing", "mining"] },
      { name: "Iron ore", tags: ["smithing", "mining"] },
      { name: "Coal", tags: ["smithing", "mining"] },
      { name: "Gold ore", tags: ["smithing", "mining"] },
      { name: "Mithril ore", tags: ["smithing", "mining"] },
      { name: "Adamantite ore", tags: ["smithing", "mining"] },
      { name: "Runite ore", tags: ["smithing", "mining"] },
      { name: "Bronze bar", tags: ["smithing"] },
      { name: "Iron bar", tags: ["smithing"] },
      { name: "Steel bar", tags: ["smithing", "construction"] },
      { name: "Gold bar", tags: ["smithing"] },
      { name: "Mithril bar", tags: ["smithing"] },
      { name: "Adamantite bar", tags: ["smithing"] },
      { name: "Runite bar", tags: ["smithing"] },
      { name: "Bronze dart tip", tags: ["smithing", "fletching"] },
      { name: "Iron dart tip", tags: ["smithing", "fletching"] },
      { name: "Steel dart tip", tags: ["smithing", "fletching"] },
      { name: "Mithril dart tip", tags: ["smithing", "fletching"] },
      { name: "Adamant dart tip", tags: ["smithing", "fletching"] },
      { name: "Rune dart tip", tags: ["smithing", "fletching"] },
      { name: "Bronze nails", tags: ["smithing", "construction"] },
      { name: "Iron nails", tags: ["smithing", "construction"] },
      { name: "Steel nails", tags: ["smithing", "construction"] },
      { name: "Mithril nails", tags: ["smithing", "construction"] },
      { name: "Adamantite nails", tags: ["smithing", "construction"] },
      { name: "Rune nails", tags: ["smithing", "construction"] },
      { name: "Steel cannonball", tags: ["smithing"] },
      { name: "Iron platebody", tags: ["smithing"] },
      { name: "Steel platebody", tags: ["smithing"] },
      { name: "Mithril platebody", tags: ["smithing"] },
      { name: "Adamant platebody", tags: ["smithing"] },
      { name: "Rune platebody", tags: ["smithing"] },
      { name: "Rune 2h sword", tags: ["smithing"] },
      { name: "Rune platelegs", tags: ["smithing"] },
      { name: "Rune plateskirt", tags: ["smithing"] },
      { name: "Rune kiteshield", tags: ["smithing"] },
      { name: "Rune battleaxe", tags: ["smithing"] },
      { name: "Rune warhammer", tags: ["smithing"] },
    ],
  },
  {
    id: "magic-skilling",
    label: "Magic & Runecraft",
    kind: "skilling",
    note: "Alching, superheat and rune inputs",
    items: [
      { name: "Nature rune", tags: ["magic", "runecraft"] },
      { name: "Law rune", tags: ["magic", "runecraft"] },
      { name: "Death rune", tags: ["magic", "runecraft"] },
      { name: "Blood rune", tags: ["magic", "runecraft"] },
      { name: "Cosmic rune", tags: ["magic", "runecraft"] },
      { name: "Astral rune", tags: ["magic", "runecraft"] },
      { name: "Fire rune", tags: ["magic", "runecraft"] },
      { name: "Chaos rune", tags: ["magic", "runecraft"] },
      { name: "Earth rune", tags: ["magic", "runecraft"] },
      { name: "Pure essence", tags: ["runecraft", "mining"] },
      { name: "Rune dart", tags: ["fletching", "magic"] },
      { name: "Yew longbow", tags: ["fletching"] },
      { name: "Magic longbow", tags: ["fletching"] },
    ],
  },
  {
    id: "farming",
    label: "Farming & Herbs",
    kind: "skilling",
    note: "Tree runs and herb patch seeds",
    items: [
      { name: "Magic seed", tags: ["farming"] },
      { name: "Palm tree seed", tags: ["farming"] },
      { name: "Yew seed", tags: ["farming"] },
      { name: "Redwood tree seed", tags: ["farming"] },
      { name: "Papaya tree seed", tags: ["farming"] },
      { name: "Ranarr seed", tags: ["farming", "herblore"] },
      { name: "Snapdragon seed", tags: ["farming", "herblore"] },
      { name: "Torstol seed", tags: ["farming", "herblore"] },
      { name: "Ultracompost", tags: ["farming"] },
      { name: "Bottomless compost bucket", tags: ["farming"] },
    ],
  },
  {
    id: "misc-skilling",
    label: "Fletching, Cooking & Agility",
    kind: "skilling",
    note: "Darts, karambwans and stamina supplies",
    items: [
      { name: "Adamant dart tip", tags: ["fletching"] },
      { name: "Rune dart tip", tags: ["fletching"] },
      { name: "Feather", tags: ["fletching"] },
      { name: "Yew logs", tags: ["fletching", "firemaking", "woodcutting"] },
      { name: "Magic logs", tags: ["fletching", "firemaking", "woodcutting"] },
      { name: "Redwood logs", tags: ["fletching", "firemaking", "woodcutting"] },
      { name: "Teak logs", tags: ["construction", "firemaking", "woodcutting"] },
      { name: "Mahogany logs", tags: ["construction", "firemaking", "woodcutting"] },
      { name: "Raw karambwan", tags: ["cooking"] },
      { name: "Raw shark", tags: ["cooking"] },
      { name: "Raw anglerfish", tags: ["cooking"] },
    ],
  }
];
