import type { CatalogGroup } from "./osrs-catalog";

export const GEAR_GROUPS: CatalogGroup[] = [

  {
    id: "melee",
    label: "Melee gear",
    kind: "gear",
    note: "Melee progression milestones",
    items: [
      { name: "Amulet of strength", tags: ["melee", "neck", "early"] },
      { name: "Combat bracelet", tags: ["melee", "hands", "early"] },
      { name: "Rune boots", tags: ["melee", "feet", "early"] },
      { name: "Berserker helm", tags: ["melee", "head", "early"] },
      { name: "Dragon scimitar", tags: ["melee", "weapon", "one-handed", "early"] },
      { name: "Dragon dagger", tags: ["melee", "weapon", "one-handed", "early"] },
      { name: "Dragon longsword", tags: ["melee", "weapon", "one-handed", "early"] },
      { name: "Dragon mace", tags: ["melee", "weapon", "one-handed", "early"] },
      { name: "Helm of neitiznot", tags: ["melee", "head", "early", "mid"] },
      { name: "Mixed hide cape", tags: ["melee", "cape", "early"] },
      { name: "Dragon boots", tags: ["melee", "feet", "early", "mid"] },
      { name: "Abyssal whip", tags: ["melee", "weapon", "one-handed", "mid"] },
      { name: "Granite maul", tags: ["melee", "weapon", "one-handed", "mid"] },
      { name: "Abyssal dagger", tags: ["melee", "weapon", "one-handed", "mid"] },
      { name: "Dragon 2h sword", tags: ["melee", "weapon", "two-handed", "mid"] },
      { name: "Kraken tentacle", tags: ["melee", "weapon", "one-handed", "mid", "late"] },
      { name: "Amulet of fury", tags: ["melee", "neck", "mid"] },
      { name: "Zamorakian hasta", tags: ["melee", "weapon", "one-handed", "mid"] },
      { name: "Zombie axe", tags: ["melee", "weapon", "two-handed", "mid"] },
      { name: "Obsidian helmet", tags: ["melee", "head", "mid"] },
      { name: "Obsidian platebody", tags: ["melee", "chest", "mid"] },
      { name: "Obsidian platelegs", tags: ["melee", "legs", "mid"] },
      { name: "Berserker necklace", tags: ["melee", "neck", "mid"] },
      { name: "Toktz-xil-ak", tags: ["melee", "weapon", "one-handed", "mid"] },
      { name: "Toktz-xil-ek", tags: ["melee", "weapon", "one-handed", "mid"] },
      { name: "Berserker ring", tags: ["melee", "ring", "mid", "late"] },
      { name: "Bellator ring", tags: ["melee", "ring", "late", "end"] },
      { name: "Tyrannical ring", tags: ["melee", "ring", "mid", "late"] },
      { name: "Treasonous ring", tags: ["melee", "ring", "mid", "late"] },
      { name: "Lightbearer", tags: ["melee", "ring", "late", "end"] },
      { name: "Ring of suffering", tags: ["melee", "ring", "late", "end"] },
      { name: "Ring of the gods", tags: ["melee", "ring", "mid", "late"] },
      { name: "Ursine chainmace", tags: ["melee", "weapon", "one-handed", "mid", "late"] },
      { name: "Dharok's helm", tags: ["melee", "head", "mid"] },
      { name: "Dharok's platebody", tags: ["melee", "chest", "mid"] },
      { name: "Dharok's platelegs", tags: ["melee", "legs", "mid"] },
      { name: "Dharok's greataxe", tags: ["melee", "weapon", "two-handed", "mid"] },
      { name: "Guthan's helm", tags: ["melee", "head", "mid"] },
      { name: "Guthan's platebody", tags: ["melee", "chest", "mid"] },
      { name: "Guthan's chainskirt", tags: ["melee", "legs", "mid"] },
      { name: "Guthan's warspear", tags: ["melee", "weapon", "two-handed", "mid"] },
      { name: "Torag's helm", tags: ["melee", "head", "mid"] },
      { name: "Torag's platebody", tags: ["melee", "chest", "mid"] },
      { name: "Torag's platelegs", tags: ["melee", "legs", "mid"] },
      { name: "Torag's hammers", tags: ["melee", "weapon", "two-handed", "mid"] },
      { name: "Verac's helm", tags: ["melee", "head", "mid"] },
      { name: "Verac's brassard", tags: ["melee", "chest", "mid"] },
      { name: "Verac's plateskirt", tags: ["melee", "legs", "mid"] },
      { name: "Verac's flail", tags: ["melee", "weapon", "one-handed", "mid"] },
      { name: "Spirit shield", tags: ["melee", "shield", "mid"] },
      { name: "Serpentine helm", tags: ["melee", "head", "late"] },
      { name: "Blood moon helm", tags: ["melee", "head", "mid", "late"] },
      { name: "Blood moon chestplate", tags: ["melee", "chest", "mid", "late"] },
      { name: "Blood moon tassets", tags: ["melee", "legs", "mid", "late"] },
      { name: "Dual macuahuitl", tags: ["melee", "weapon", "two-handed", "mid", "late"] },
      { name: "Amulet of torture", tags: ["melee", "neck", "late"] },
      { name: "Bandos chestplate", tags: ["melee", "chest", "late"] },
      { name: "Bandos tassets", tags: ["melee", "legs", "late"] },
      { name: "Bandos boots", tags: ["melee", "feet", "late"] },
      { name: "Primordial boots", tags: ["melee", "feet", "late", "end"] },
      { name: "Ferocious gloves", tags: ["melee", "hands", "late", "end"] },
      { name: "Neitiznot faceguard", tags: ["melee", "head", "late"] },
      { name: "Sunfire fanatic helm", tags: ["melee", "head", "mid", "late"] },
      { name: "Sunfire fanatic cuirass", tags: ["melee", "chest", "mid", "late"] },
      { name: "Sunfire fanatic chausses", tags: ["melee", "legs", "mid", "late"] },
      { name: "Burning claws", tags: ["melee", "weapon", "two-handed", "late"] },
      { name: "Osmumten's fang", tags: ["melee", "weapon", "one-handed", "late"] },
      { name: "Abyssal bludgeon", tags: ["melee", "weapon", "two-handed", "late"] },
      { name: "Dragon warhammer", tags: ["melee", "weapon", "one-handed", "late"] },
      { name: "Keris partisan", tags: ["melee", "weapon", "two-handed", "late"] },
      { name: "Elder maul", tags: ["melee", "weapon", "two-handed", "late"] },
      { name: "Blessed spirit shield", tags: ["melee", "shield", "late"] },
      { name: "Avernic defender hilt", tags: ["melee", "shield", "late", "end"] },
      { name: "Dragonfire shield", tags: ["melee", "shield", "late"] },
      { name: "Bandos godsword", tags: ["melee", "weapon", "two-handed", "late"] },
      { name: "Saradomin godsword", tags: ["melee", "weapon", "two-handed", "late"] },
      { name: "Armadyl godsword", tags: ["melee", "weapon", "two-handed", "late"] },
      { name: "Zamorak godsword", tags: ["melee", "weapon", "two-handed", "late"] },
      { name: "Ancient godsword", tags: ["melee", "weapon", "two-handed", "late"] },
      { name: "Dragon hunter lance", tags: ["melee", "weapon", "one-handed", "late"] },
      { name: "Voidwaker", tags: ["melee", "weapon", "one-handed", "late"] },
      { name: "Dragon claws", tags: ["melee", "weapon", "two-handed", "late"] },
      { name: "Noxious halberd", tags: ["melee", "weapon", "two-handed", "late"] },
      { name: "Ghrazi rapier", tags: ["melee", "weapon", "one-handed", "late", "end"] },
      { name: "Dinh's bulwark", tags: ["melee", "weapon", "two-handed", "end"] },
      { name: "Elysian spirit shield", tags: ["melee", "shield", "end"] },
      { name: "Justiciar faceguard", tags: ["melee", "head", "end"] },
      { name: "Justiciar chestguard", tags: ["melee", "chest", "end"] },
      { name: "Justiciar legguards", tags: ["melee", "legs", "end"] },
      { name: "Inquisitor's great helm", tags: ["melee", "head", "end"] },
      { name: "Inquisitor's hauberk", tags: ["melee", "chest", "end"] },
      { name: "Inquisitor's plateskirt", tags: ["melee", "legs", "end"] },
      { name: "Inquisitor's mace", tags: ["melee", "weapon", "one-handed", "end"] },
      { name: "Scythe of Vitur (uncharged)", tags: ["melee", "weapon", "two-handed", "end"] },
      { name: "Soulreaper axe", tags: ["melee", "weapon", "two-handed", "end"] },
      { name: "Blade of Saeldor (inactive)", tags: ["melee", "weapon", "one-handed", "end"] },
      { name: "Amulet of rancour", tags: ["melee", "neck", "end"] },
      { name: "Amulet of blood fury", tags: ["melee", "neck", "end"] },
      { name: "Torva full helm", tags: ["melee", "head", "end"] },
      { name: "Torva platebody", tags: ["melee", "chest", "end"] },
      { name: "Torva platelegs", tags: ["melee", "legs", "end"] },
      { name: "Ultor ring", tags: ["melee", "ring", "end"] },
      { name: "Avernic treads", tags: ["melee", "feet", "end"] },
      { name: "Oathplate helm", tags: ["melee", "head", "end"] },
      { name: "Oathplate chest", tags: ["melee", "chest", "end"] },
      { name: "Oathplate legs", tags: ["melee", "legs", "end"] },
      { name: "3rd age full helmet", tags: ["melee", "head", "end"] },
      { name: "3rd age platebody", tags: ["melee", "chest", "end"] },
      { name: "3rd age platelegs", tags: ["melee", "legs", "end"] },
      { name: "3rd age plateskirt", tags: ["melee", "legs", "end"] },
      { name: "3rd age kiteshield", tags: ["melee", "shield", "end"] },
      { name: "3rd age longsword", tags: ["melee", "weapon", "one-handed", "end"] },
      { name: "Torn prayer scroll", tags: ["melee", "prayer", "mid", "late", "end"] },
    ],
  },
  {
    id: "ranged",
    label: "Ranged gear",
    kind: "gear",
    note: "Ranged progression milestones",
    items: [
      { name: "Maple shortbow", tags: ["range", "weapon", "two-handed", "early"] },
      { name: "Magic shortbow", tags: ["range", "weapon", "two-handed", "early", "mid"] },
      { name: "Rune crossbow", tags: ["range", "weapon", "one-handed", "early", "mid"] },
      { name: "Dorgeshuun crossbow", tags: ["range", "weapon", "one-handed", "early"] },
      { name: "Dragon crossbow", tags: ["range", "weapon", "one-handed", "mid", "late"] },
      { name: "Toxic blowpipe (empty)", tags: ["range", "weapon", "two-handed", "mid", "late"] },
      { name: "Twisted buckler", tags: ["range", "shield", "late"] },
      { name: "Odium ward", tags: ["range", "shield", "mid", "late"] },
      { name: "Antler guard", tags: ["range", "shield", "mid"] },
      { name: "Karil's coif", tags: ["range", "head", "mid"] },
      { name: "Karil's crossbow", tags: ["range", "weapon", "one-handed", "mid"] },
      { name: "Karil's leathertop", tags: ["range", "chest", "mid"] },
      { name: "Karil's leatherskirt", tags: ["range", "legs", "mid"] },
      { name: "Eclipse atlatl", tags: ["range", "weapon", "one-handed", "mid", "late"] },
      { name: "Eclipse moon helm", tags: ["range", "head", "mid", "late"] },
      { name: "Eclipse moon chestplate", tags: ["range", "chest", "mid", "late"] },
      { name: "Eclipse moon tassets", tags: ["range", "legs", "mid", "late"] },
      { name: "Hunters' sunlight crossbow", tags: ["range", "weapon", "one-handed", "mid"] },
      { name: "Armadyl crossbow", tags: ["range", "weapon", "one-handed", "late"] },
      { name: "Armadyl helmet", tags: ["range", "head", "late"] },
      { name: "Armadyl chestplate", tags: ["range", "chest", "late"] },
      { name: "Armadyl chainskirt", tags: ["range", "legs", "late"] },
      { name: "Necklace of anguish", tags: ["range", "neck", "late", "end"] },
      { name: "Pegasian boots", tags: ["range", "feet", "late", "end"] },
      { name: "Dragon hunter crossbow", tags: ["range", "weapon", "one-handed", "late"] },
      { name: "Dragonfire ward", tags: ["range", "shield", "late"] },
      { name: "Webweaver bow (u)", tags: ["range", "weapon", "two-handed", "late"] },
      { name: "Scorching bow", tags: ["range", "weapon", "two-handed", "late"] },
      { name: "Bow of faerdhinen (inactive)", tags: ["range", "weapon", "two-handed", "late", "end"] },
      { name: "Crystal helm", tags: ["range", "head", "late"] },
      { name: "Crystal body", tags: ["range", "chest", "late"] },
      { name: "Crystal legs", tags: ["range", "legs", "late"] },
      { name: "Twisted bow", tags: ["range", "weapon", "two-handed", "end"] },
      { name: "Zaryte crossbow", tags: ["range", "weapon", "one-handed", "end"] },
      { name: "Venator bow (uncharged)", tags: ["range", "weapon", "two-handed", "end"] },
      { name: "Masori mask", tags: ["range", "head", "end"] },
      { name: "Masori body", tags: ["range", "chest", "end"] },
      { name: "Masori chaps", tags: ["range", "legs", "end"] },
      { name: "Masori mask (f)", tags: ["range", "head", "end"] },
      { name: "Masori body (f)", tags: ["range", "chest", "end"] },
      { name: "Masori chaps (f)", tags: ["range", "legs", "end"] },
      { name: "Zaryte vambraces", tags: ["range", "hands", "end"] },
      { name: "Venator ring", tags: ["range", "ring", "end"] },
      { name: "Archers ring", tags: ["range", "ring", "mid", "late"] },
      { name: "Lightbearer", tags: ["range", "ring", "late", "end"] },
      { name: "Ring of suffering", tags: ["range", "ring", "late", "end"] },
      { name: "Ring of the gods", tags: ["range", "ring", "mid", "late"] },
      { name: "Sunfire fanatic helm", tags: ["range", "head", "mid", "late"] },
      { name: "Sunfire fanatic cuirass", tags: ["range", "chest", "mid", "late"] },
      { name: "Sunfire fanatic chausses", tags: ["range", "legs", "mid", "late"] },
      { name: "Necklace of rupture", tags: ["range", "neck", "end"] },
      { name: "Avernic treads", tags: ["range", "feet", "end"] },
      { name: "3rd age range coif", tags: ["range", "head", "end"] },
      { name: "3rd age range top", tags: ["range", "chest", "end"] },
      { name: "3rd age range legs", tags: ["range", "legs", "end"] },
      { name: "3rd age vambraces", tags: ["range", "hands", "end"] },
      { name: "3rd age bow", tags: ["range", "weapon", "two-handed", "end"] },
      { name: "Dexterous prayer scroll", tags: ["range", "prayer", "late", "end"] },
      { name: "Torn prayer scroll", tags: ["range", "prayer", "mid", "late", "end"] },
    ],
  },
  {
    id: "magic",
    label: "Magic gear",
    kind: "gear",
    note: "Magic progression milestones",
    items: [
      { name: "Mystic hat (dark)", tags: ["magic", "head", "early"] },
      { name: "Mystic robe top (dark)", tags: ["magic", "chest", "early"] },
      { name: "Mystic robe bottom (dark)", tags: ["magic", "legs", "early"] },
      { name: "Mystic gloves (dark)", tags: ["magic", "hands", "early"] },
      { name: "Mystic boots (dark)", tags: ["magic", "feet", "early"] },
      { name: "Fire battlestaff", tags: ["magic", "weapon", "two-handed", "early"] },
      { name: "Water battlestaff", tags: ["magic", "weapon", "two-handed", "early"] },
      { name: "Earth battlestaff", tags: ["magic", "weapon", "two-handed", "early"] },
      { name: "Air battlestaff", tags: ["magic", "weapon", "two-handed", "early"] },
      { name: "Mystic fire staff", tags: ["magic", "weapon", "two-handed", "early", "mid"] },
      { name: "Mystic water staff", tags: ["magic", "weapon", "two-handed", "early", "mid"] },
      { name: "Mystic earth staff", tags: ["magic", "weapon", "two-handed", "early", "mid"] },
      { name: "Mystic air staff", tags: ["magic", "weapon", "two-handed", "early", "mid"] },
      { name: "Infinity hat", tags: ["magic", "head", "mid"] },
      { name: "Infinity top", tags: ["magic", "chest", "mid"] },
      { name: "Infinity bottoms", tags: ["magic", "legs", "mid"] },
      { name: "Infinity gloves", tags: ["magic", "hands", "mid"] },
      { name: "Infinity boots", tags: ["magic", "feet", "mid"] },
      { name: "Bloodbark helm", tags: ["magic", "head", "mid"] },
      { name: "Bloodbark body", tags: ["magic", "chest", "mid"] },
      { name: "Bloodbark legs", tags: ["magic", "legs", "mid"] },
      { name: "Bloodbark gauntlets", tags: ["magic", "hands", "mid"] },
      { name: "Bloodbark boots", tags: ["magic", "feet", "mid"] },
      { name: "Dagon'hai hat", tags: ["magic", "head", "mid"] },
      { name: "Dagon'hai robe top", tags: ["magic", "chest", "mid"] },
      { name: "Dagon'hai robe bottom", tags: ["magic", "legs", "mid"] },
      { name: "Warped sceptre", tags: ["magic", "weapon", "one-handed", "mid"] },
      { name: "Ancient staff", tags: ["magic", "weapon", "one-handed", "mid"] },
      { name: "Iban's staff (u)", tags: ["magic", "weapon", "two-handed", "early", "mid"] },
      { name: "Ahrim's hood", tags: ["magic", "head", "mid"] },
      { name: "Ahrim's robetop", tags: ["magic", "chest", "mid"] },
      { name: "Ahrim's robeskirt", tags: ["magic", "legs", "mid"] },
      { name: "Ahrim's staff", tags: ["magic", "weapon", "two-handed", "mid"] },
      { name: "Trident of the seas (full)", tags: ["magic", "weapon", "one-handed", "mid"] },
      { name: "Uncharged trident", tags: ["magic", "weapon", "one-handed", "mid"] },
      { name: "Uncharged toxic trident", tags: ["magic", "weapon", "one-handed", "mid", "late"] },
      { name: "Occult necklace", tags: ["magic", "neck", "mid", "late"] },
      { name: "Seers ring", tags: ["magic", "ring", "mid", "late"] },
      { name: "Master wand", tags: ["magic", "weapon", "one-handed", "mid"] },
      { name: "Lightbearer", tags: ["magic", "ring", "late", "end"] },
      { name: "Ring of suffering", tags: ["magic", "ring", "late", "end"] },
      { name: "Ring of the gods", tags: ["magic", "ring", "mid", "late"] },
      { name: "Sunfire fanatic helm", tags: ["magic", "head", "mid", "late"] },
      { name: "Sunfire fanatic cuirass", tags: ["magic", "chest", "mid", "late"] },
      { name: "Sunfire fanatic chausses", tags: ["magic", "legs", "mid", "late"] },
      { name: "Mage's book", tags: ["magic", "shield", "mid", "late"] },
      { name: "Tome of fire", tags: ["magic", "shield", "mid", "late"] },
      { name: "Tome of water", tags: ["magic", "shield", "mid", "late"] },
      { name: "Tome of earth", tags: ["magic", "shield", "mid", "late"] },
      { name: "Blue moon helm", tags: ["magic", "head", "mid", "late"] },
      { name: "Blue moon chestplate", tags: ["magic", "chest", "mid", "late"] },
      { name: "Blue moon tassets", tags: ["magic", "legs", "mid", "late"] },
      { name: "Ancient sceptre", tags: ["magic", "weapon", "one-handed", "mid", "late"] },
      { name: "Staff of light", tags: ["magic", "weapon", "one-handed", "mid", "late"] },
      { name: "Staff of the dead", tags: ["magic", "weapon", "one-handed", "mid", "late"] },
      { name: "Toxic staff (uncharged)", tags: ["magic", "weapon", "two-handed", "late"] },
      { name: "Dragon hunter wand", tags: ["magic", "weapon", "one-handed", "late"] },
      { name: "Purging staff", tags: ["magic", "weapon", "two-handed", "late"] },
      { name: "Sanguinesti staff (uncharged)", tags: ["magic", "weapon", "one-handed", "late"] },
      { name: "Eye of ayak (uncharged)", tags: ["magic", "weapon", "one-handed", "late"] },
      { name: "Elidinis' ward", tags: ["magic", "shield", "late"] },
      { name: "Ancient wyvern shield", tags: ["magic", "shield", "late"] },
      { name: "Elidinis' ward (f)", tags: ["magic", "shield", "end"] },
      { name: "Eternal boots", tags: ["magic", "feet", "late", "end"] },
      { name: "Tormented bracelet", tags: ["magic", "hands", "late", "end"] },
      { name: "Virtus mask", tags: ["magic", "head", "late", "end"] },
      { name: "Virtus robe top", tags: ["magic", "chest", "late", "end"] },
      { name: "Virtus robe bottom", tags: ["magic", "legs", "late", "end"] },
      { name: "Ancestral hat", tags: ["magic", "head", "end"] },
      { name: "Ancestral robe top", tags: ["magic", "chest", "end"] },
      { name: "Ancestral robe bottom", tags: ["magic", "legs", "end"] },
      { name: "Kodai wand", tags: ["magic", "weapon", "one-handed", "end"] },
      { name: "Nightmare staff", tags: ["magic", "weapon", "two-handed", "end"] },
      { name: "Arcane spirit shield", tags: ["magic", "shield", "end"] },
      { name: "Spectral spirit shield", tags: ["magic", "shield", "end"] },
      { name: "Tumeken's shadow (uncharged)", tags: ["magic", "weapon", "two-handed", "end"] },
      { name: "Confliction gauntlets", tags: ["magic", "hands", "end"] },
      { name: "Magus ring", tags: ["magic", "ring", "end"] },
      { name: "Avernic treads", tags: ["magic", "feet", "end"] },
      { name: "3rd age mage hat", tags: ["magic", "head", "end"] },
      { name: "3rd age robe top", tags: ["magic", "chest", "end"] },
      { name: "3rd age robe", tags: ["magic", "legs", "end"] },
      { name: "3rd age amulet", tags: ["magic", "neck", "end"] },
      { name: "Arcane prayer scroll", tags: ["magic", "prayer", "late", "end"] },
      { name: "Torn prayer scroll", tags: ["magic", "prayer", "mid", "late", "end"] },
    ],
  },
  {
    id: "utility",
    label: "Utility & supplies",
    kind: "gear",
    note: "Consumables, ammo, and everyday kit",
    items: [
      { name: "Saradomin brew(4)", tags: ["supplies", "potion"] },
      { name: "Zamorak brew(4)", tags: ["supplies", "potion"] },
      { name: "Ancient brew(4)", tags: ["supplies", "potion"] },
      { name: "Forgotten brew(4)", tags: ["supplies", "potion"] },
      { name: "Super restore(4)", tags: ["supplies", "potion"] },
      { name: "Prayer potion(4)", tags: ["supplies", "potion"] },
      { name: "Sanfew serum(4)", tags: ["supplies", "potion"] },
      { name: "Menaphite remedy(4)", tags: ["supplies", "potion"] },
      { name: "Ranging potion(4)", tags: ["supplies", "potion"] },
      { name: "Magic potion(4)", tags: ["supplies", "potion"] },
      { name: "Bastion potion(4)", tags: ["supplies", "potion"] },
      { name: "Battlemage potion(4)", tags: ["supplies", "potion"] },
      { name: "Super combat potion(4)", tags: ["supplies", "potion"] },
      { name: "Divine super combat potion(4)", tags: ["supplies", "potion"] },
      { name: "Divine bastion potion(4)", tags: ["supplies", "potion"] },
      { name: "Divine magic potion(4)", tags: ["supplies", "potion"] },
      { name: "Stamina potion(4)", tags: ["supplies", "potion"] },
      { name: "Extended stamina potion(4)", tags: ["supplies", "potion"] },
      { name: "Extended antifire(4)", tags: ["supplies", "potion"] },
      { name: "Extended super antifire(4)", tags: ["supplies", "potion"] },
      { name: "Anti-venom+(4)", tags: ["supplies", "potion"] },
      { name: "Guthix rest(4)", tags: ["supplies", "potion"] },
      { name: "Saturated heart", tags: ["supplies", "potion"] },
      { name: "Imbued heart", tags: ["supplies", "potion"] },
      { name: "Anglerfish", tags: ["supplies", "food"] },
      { name: "Shark", tags: ["supplies", "food"] },
      { name: "Manta ray", tags: ["supplies", "food"] },
      { name: "Dark crab", tags: ["supplies", "food"] },
      { name: "Marlin", tags: ["supplies", "food"] },
      { name: "Haddock", tags: ["supplies", "food"] },
      { name: "Cooked karambwan", tags: ["supplies", "food"] },
      { name: "Blighted karambwan", tags: ["supplies", "food"] },
      { name: "Cooked moonlight antelope", tags: ["supplies", "food"] },
      { name: "Cooked dashing kebbit", tags: ["supplies", "food"] },
      { name: "Amulet of glory(6)", tags: ["supplies", "neck"] },
      { name: "Zulrah's scales", tags: ["supplies"] },
      { name: "Revenant ether", tags: ["supplies"] },
      { name: "Adamant arrow", tags: ["supplies", "ammo"] },
      { name: "Rune arrow", tags: ["supplies", "ammo"] },
      { name: "Amethyst arrow", tags: ["supplies", "ammo"] },
      { name: "Dragon arrow", tags: ["supplies", "ammo"] },
      { name: "Bone bolts", tags: ["supplies", "ammo"] },
      { name: "Broad bolts", tags: ["supplies", "ammo"] },
      { name: "Diamond bolts (e)", tags: ["supplies", "ammo"] },
      { name: "Ruby bolts (e)", tags: ["supplies", "ammo"] },
      { name: "Sunlight antler bolts", tags: ["supplies", "ammo"] },
      { name: "Moonlight antler bolts", tags: ["supplies", "ammo"] },
      { name: "Ruby dragon bolts (e)", tags: ["supplies", "ammo"] },
      { name: "Diamond dragon bolts (e)", tags: ["supplies", "ammo"] },
      { name: "Adamant dart", tags: ["supplies", "ammo"] },
      { name: "Rune dart", tags: ["supplies", "ammo"] },
      { name: "Amethyst dart", tags: ["supplies", "ammo"] },
      { name: "Dragon dart", tags: ["supplies", "ammo"] },
      { name: "Atlatl dart", tags: ["supplies", "ammo"] },
      { name: "Red chinchompa", tags: ["supplies", "ammo"] },
      { name: "Black chinchompa", tags: ["supplies", "ammo"] },
      { name: "Steel cannonball", tags: ["supplies", "ammo"] },
      { name: "Tormented synapse", tags: ["supplies"] },
      { name: "Elysian sigil", tags: ["supplies"] },
      { name: "Arcane sigil", tags: ["supplies"] },
      { name: "Spectral sigil", tags: ["supplies"] },
      { name: "Kodai insignia", tags: ["supplies"] },
      { name: "Harmonised orb", tags: ["supplies"] },
      { name: "Volatile orb", tags: ["supplies"] },
      { name: "Eldritch orb", tags: ["supplies"] },
      { name: "Primordial crystal", tags: ["supplies"] },
      { name: "Pegasian crystal", tags: ["supplies"] },
      { name: "Eternal crystal", tags: ["supplies"] },
      { name: "Hydra leather", tags: ["supplies"] },
      { name: "Blood shard", tags: ["supplies"] },
      { name: "Ancient hilt", tags: ["supplies"] },
    ],
  },
];
